apiVersion: v1
kind: ConfigMap
metadata:
  name: tubearchivist-configmap
  namespace: tubearchivist
data:
  TA_HOST: localhost
  TA_PORT: 8000 # default
  TA_USERNAME: "sito"
  TA_PASSWORD: "sito_password"
  TZ: Europe/Madrid