apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tubearchivist
resources:
  - deployment.yaml
  - namespace.yaml
  - storage.yaml
  - service.yaml
  - configmap.yaml
  # - secrets.yaml
  # - networking.yaml
