namespaceOverride: "kube-system"

kubeProxyReplacement: true

operator:
  replicas: 1

envoyConfig:
  enabled: false

ingressController:
  enabled: false

gatewayAPI:
  enabled: false

loadBalancer:
  l7:
    backend: ""
#    backend: envoy

bgpControlPlane:
  enabled: true
