namespaceOverride: "kube-system"

kubeProxyReplacement: true

k8sServiceHost: 192.168.1.141
k8sServicePort: 6443

operator:
  replicas: 1

envoyConfig:
  enabled: true

routingMode: native
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: "10.42.0.0/16"
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]

ingressController:
  enabled: false
  # loadbalancerMode: "shared"
  # default: true

loadBalancer:
  mode: "dsr"
  l7:
    backend: "envoy"

gatewayAPI:
  enabled: false

l2announcements:
  enabled: true

bgpControlPlane:
  enabled: true

ipv4:
  enabled: true
  masquerade: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true