apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - mariadb-storage.yaml
  - mariadb-service.yaml
  - mariadb-deployment.yaml
  - deployment.yaml
  - configmap.yaml
  - ingress.yaml
  - secret.yaml
  - service.yaml
  - storage.yaml
